// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu94FTXJz_GdzHHGxKzk2jMwyRvYgK0m8',
    appId: '1:535650634961:web:86ecf99b28c8c7fe4909f0',
    messagingSenderId: '535650634961',
    projectId: 'doctorappointmentapp-6071e',
    authDomain: 'doctorappointmentapp-6071e.firebaseapp.com',
    storageBucket: 'doctorappointmentapp-6071e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRxmRpeAAQzVJZq6xk52KWN0ONBcbva7g',
    appId: '1:535650634961:android:050dd75de4970bc64909f0',
    messagingSenderId: '535650634961',
    projectId: 'doctorappointmentapp-6071e',
    storageBucket: 'doctorappointmentapp-6071e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClbMYVNeGp7rwhZJhz3vcVAZvHl4D3FbA',
    appId: '1:535650634961:ios:cf0dd0badc0d534a4909f0',
    messagingSenderId: '535650634961',
    projectId: 'doctorappointmentapp-6071e',
    storageBucket: 'doctorappointmentapp-6071e.firebasestorage.app',
    iosBundleId: 'com.example.loginAplipacion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClbMYVNeGp7rwhZJhz3vcVAZvHl4D3FbA',
    appId: '1:535650634961:ios:cf0dd0badc0d534a4909f0',
    messagingSenderId: '535650634961',
    projectId: 'doctorappointmentapp-6071e',
    storageBucket: 'doctorappointmentapp-6071e.firebasestorage.app',
    iosBundleId: 'com.example.loginAplipacion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu94FTXJz_GdzHHGxKzk2jMwyRvYgK0m8',
    appId: '1:535650634961:web:ce2d56fb8478dc7b4909f0',
    messagingSenderId: '535650634961',
    projectId: 'doctorappointmentapp-6071e',
    authDomain: 'doctorappointmentapp-6071e.firebaseapp.com',
    storageBucket: 'doctorappointmentapp-6071e.firebasestorage.app',
  );
}
